
rm(list = ls())
set.seed(290875)
options(prompt = "R> ", width = 63, # digits = 4, 
    SweaveHooks = list(leftpar = function() 
        par(mai = par("mai") * c(1, 1.05, 1, 1))))
### </FIXME> hm, R-2.4.0 --vanilla seems to need this
a <- Sys.setlocale("LC_ALL", "C")
### </FIXME>
cat("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n")
cat("%% DO NOT EDIT THIS FILE !!! %%%%\n")
cat("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n")
cat("\\pagestyle{headings}\n")